log4j.rootLogger=info,stdout
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
#dwr log config
# Pattern to output the caller's file name and line number.
log4j.appender.stdout.layout.ConversionPattern=%5p [%t] (%F:%L) %d{HH:mm:ss,SSS} -- %m%n


log4j.logger.org.hibernate=debug

# Log JDBC parameters
log4j.logger.org.hibernate.type=debug
#c3p0  
#log4j.logger.com.mchange.v2.resourcepool.BasicResourcePool=WARN
log4j.logger.com.mchange.v2=error
  

